### ISSUE TITLE
Link to "Book a Cab" leads to a 404

### ISSUE THREAD

**Issue by KentShikama** [aspc/5C-Ride-Share#3]
The link points to `http://www.pomona.edu/administration/dean-of-students/new-students/guidebook/introductions/arrival-info.aspx`

**Comment by alokedesai** [comment]
@aspc/digital-media-and-programming-group  What are you thoughts on this? One option is to just return https://www.ridecharge.com/s/ca-los-angeles/taxi/branded/la_yellow since. Pomona no longer has discount codes on their site for a super shuttle or a taxi.

**Comment by ZiqiXiong** [comment]
(y)

**Comment by ZiqiXiong** [comment]
:+1:

**Comment by KentShikama** [comment]
Sounds good to me

**Comment by mattdahl** [comment]
Good catch! Do we care about which taxi company we send traffic to? Maybe it would be better to redirect to their generic index page for LA taxies instead? (https://www.ridecharge.com/s/ca-los-angeles)

**Comment by alokedesai** [comment]
Yeah agreed, I think that makes more sense. @ZiqiXiong want to take this on as super simple starter bug and to make sure Kent's new dev workflow works?

**Comment by ZiqiXiong** [comment]
Sure thing!

**Comment by KentShikama** [comment]
See https://github.com/aspc/5C-Ride-Share/pull/5
