### ISSUE TITLE
Rides are limited to past years

### ISSUE THREAD

**Issue by Mer-cat** [aspc/5C-Ride-Share#30]
Currently, ASPC Rideshare is unusable because the only years to put in a ride for are 2019-2020. It would be great if this could be updated so that users can carpool again, especially for the upcoming breaks.

I think I found the problem on this line, but I have no experience in this language so thought it best to leave this issue to someone familiar:
https://github.com/aspc/5C-Ride-Share/blob/254528590ebcb8cabbc4e809bdc4aca1c7e7ef92/app/views/rides/_form.html.erb#L74

Similar issue of 2019-2020 only for rest of the datetime_selects in the form.

**Comment by adamguos** [comment]
Fixed in commit 1ad6a47be2add8e1c0a169855d44208825e2238b, thanks!
