### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by frozenpandaman** [aspc/5C-Ride-Share#9]
In `app/views/sessions/failure.html.erb`, the text should read "Your Facebook login," not "You're."

**Comment by KentShikama** [comment]
@frozenpandaman You want to go ahead and submit a PR?

**Comment by frozenpandaman** [comment]
@KentShikama hehehe i was lazy so i just submitted it as an issue instead, but sure, i'll do it in a sec. :P

**Comment by frozenpandaman** [comment]
@KentShikama ok for some reason there are other commits in here from, like, 2015, even though i made my fork all in-line w/ the upstream repo (this one) but w/e hopefully this should work 😑 #10

**Comment by KentShikama** [comment]
It is because you merged master into your old PR branch and then kept working from there. Can you simply checkout origin/master, create a new branch, and then commit your fix on your new branch?

**Comment by KentShikama** [comment]
`git log --graph --decorate --all` might help

**Comment by frozenpandaman** [comment]
that's the fanciest git command i've ever heard of
